cookie:
  expiry_days: 0
  key: nueces_ia_vitakai
  name: nuecesia_nativa
credentials:
  usernames:
    juana:
      email: juana@nativatraders.com
      name: Juana
      password: $2b$12$kIynAHQOEK0mzM9YHtNGbuXRQxlgDX1UHLV7oitX/sdbt.CWggcnG
    kedar:
      email: kedar@nativatraders.com
      name: Kedar
      password: $2b$12$kIynAHQOEK0mzM9YHtNGbuXRQxlgDX1UHLV7oitX/sdbt.CWggcnG
    gabriel:
      email: gabriel@nativatraders.com
      name: Gabriel
      password: $2b$12$kIynAHQOEK0mzM9YHtNGbuXRQxlgDX1UHLV7oitX/sdbt.CWggcnG
    cristina:
      email: cherrera@vitakai.com
      name: Cristina
      password: $2b$12$kIynAHQOEK0mzM9YHtNGbuXRQxlgDX1UHLV7oitX/sdbt.CWggcnG
preauthorized:
  emails:
  - cgonzalez@vitakai.com
  - cherrera@vitakai.com
  - jdonoso@vitakai.com
  - mrosas@pintopiga.com